name: ChatWatchdog
version: '${project.version}'
main: cc.synkdev.chatWatchdog.bukkit.ChatWatchdog
api-version: '1.13'
authors: [ Synk ]
depend:
  - NexusCore
commands:
  chatwatchdog:
    description: "Main plugin command"
    usage: "/chatwatchdog"
    aliases:
      - "cw"
      - "watchdog"
